name: Generate Changelog
on:
  push:
    branches:
      - main

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'

      - name: Install dependencies
        run: npm install generate-changelog

      - name: Generate Changelog
        run: npm run generate-changelog

      - name: Commit Changelog
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add changelog.md
          git commit -m "Update changelog [skip ci]"
          git push
