name: Generate Changelog

on: [push, pull_request]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'

      - name: Install dependencies
        run: npm install generate-changelog

      - name: Generate Changelog
        run: npm run generate-changelog

      - name: Commit Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add CHANGELOG.md
          git commit -m "Update changelog [skip ci]" || echo "No changes to commit"
          git push origin HEAD
