---
name: Generate JSDocs

on:
  push:
    branches-ignore:
      - main  # This ensures it does not run on the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Generate JSDocs
        run: npx jsdoc -r ./src/ -d docs

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "Update JSDocs" || echo "No changes to commit"
          git push https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
